Added Functionality for Adding Bounds to Burst Capture
ctlusto/gifsmos pull request #30
Opened 2019-06-17 23:54 UTC by danieljaeim

As per the issue outlined similarly with (#7), here we have functionality added to allow the user to specify bounds for when they are capturing a bunch of images in rapid succession using the BURST Capture functionality. 

Here, I added additional functionality to allow the user to extend the bounds they've set in the settings pane to now be recognized by the BURST Capture Component. Now the Burst Component will recognize taking a series of images, just as if the user had individually pushed them using the Camera Capture component.

2019-06-19 18:52 UTC, japamat commented on src/components/Settings.css
> +.Settings-dropdown {
Similar to the `.Settings-input`, you could add `outline: none !important;` to prevent the dropdown showing an outline on focus

2019-06-19 19:15 UTC, japamat commented on src/lib/input-helpers.js
> +  if (isNaN(top)) errors['top'] = true;
Maybe 49 - 52 could be accomplished with a `for.. in` loop:
```
for (let cur in inputs) {
  if (isNaN(inputs[cur])) errors[cur] = true;
} 
```

2019-06-19 19:16 UTC, japamat commented on src/components/Burst.js
> +import panes from '../constants/pane-types';
`panes` is never used, you can get rid of this

2019-06-19 19:17 UTC, japamat commented on src/lib/error-messages.js
> +        break;
this `switch` function should have a `default` case

2019-06-19 19:54 UTC, japamat commented on src/lib/error-messages.js
> +  if (propText === propMap.idx) {
I've noticed elsewhere in the code that for single return if cases, you don't need to wrap the logic in curly braces, i.e.

```
if (propText === propMap.idx)
  return `Your ${propText} must be a positive integer.`;
```

2019-06-21 17:25 UTC, misscoded requested changes
See comments.

2019-06-21 17:25 UTC, alissarenz commented on src/actions/index.js
> +    console.log('burst error');
Remove console.log

2019-06-21 17:25 UTC, alissarenz commented on src/actions/index.js
> +    console.log('setting error');
Remove console.log

2019-06-21 17:25 UTC, alissarenz commented on src/actions/index.js
> +    console.log('bound error', top, bottom, left, right);
Remove console.log

2019-06-21 17:25 UTC, alissarenz commented on src/components/App.js
> +    //allows us to see calculator object in window
Unnecessary comment

2019-06-21 17:25 UTC, alissarenz commented on .env
> +SKIP_PREFLIGHT_CHECK=true
.env has got to go.

2019-07-08 16:56 UTC, merged